bugtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('account/signup', views.signup, name='signup'),
    path('projects/', views.projects_index, name='index'),
    path('projects/create/', views.add_project, name='project_create'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/add_teammates', views.add_teammates, name='add_teammates'),
    path('bugs/create/<int:project_id>/', views.add_bug_to_project, name='project_bug_create'),
    path('bugs/create/', views.create_bug, name='create_bug'),
    path('bugs/<int:bug_id>/resolve/', views.resolve_bug, name='resolve_bug'),
    path('bugs/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    path('bugs/<int:bug_id>/add_screenshot/', views.add_screenshot, name='add_screenshot'),
    path('bugs/<int:bug_id>/add_comment/', views.add_comment, name='add_comment'),
    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=254)


class Project(models.Model):
    name = models.CharField(max_length=50)
    teammates = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project_detail', kwargs={'project_id': self.id})

class Bug(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    file_name = models.CharField(max_length=50)
    resolved = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    # mark as new bug for users
    seen_by = models.ManyToManyField(User, related_name='seen_by_bug_set')
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bug_detail', kwargs={'bug_id': self.id})

class Comment(models.Model):
    text = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['created_at']


class Screenshot(models.Model):
    url = models.CharField(max_length=200)
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Screenshot for bug_id: {self.bug_id} @{self.url}"

    class Meta:
        ordering = ['created_at']

main_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Project, Bug


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required')

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', )

    # def __init__(self):
    #     super(SignUpForm, self).__init__()
    #     self.fields['email'].widget.attrs.update({'autofocus': 'autofocus',
    #         'required': 'required'})

class BugForm(ModelForm):
    class Meta:
        model = Bug
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from .models import Project, Bug, Screenshot
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
import boto3

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings

S3_BASE_URL = "https://pp-bugtracker.s3.amazonaws.com/"
BUCKET = "pp-bugtracker"

# HELPER FUNCTION

def generate_username(email):
    username = email.split('@')[0]
    try:
      user_with_existing_username = User.objects.get(username = username)
      print(f'user with existing username = {user_with_existing_username}')
      if user_with_existing_username:
        username += '1'
    except:
      pass
    return username


# VIEWS

def home(request):
  return redirect('index')

def signup(request):
    error_message = ''
    if request.method == 'POST':
        print(request.POST)
         # Create a user form object
         # that includes data from the browser
        form = SignUpForm(request.POST)
        if form.is_valid():
            # add user to database
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up, try again!'
    # either a bad POST request, or a GET request
    # just render the empty form
    form = SignUpForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

@login_required
def projects_index(request):
    projects = Project.objects.filter(teammates=request.user)
    unresolved_bugs = []
    resolved_bugs = []
    for project in projects:
      for bug in project.bug_set.all():
        if bug.resolved == False:
          unresolved_bugs.append(bug)
        else:
          resolved_bugs.append(bug)
    return render(request, 'projects/index.html', {
      'projects': projects, 
      'unresolved_bugs': unresolved_bugs,
      'resolved_bugs': resolved_bugs
      })

@login_required
def add_teammates(request, project_id):
    projects = Project.objects.filter(teammates=request.user)
    project = Project.objects.get(id=project_id)
    user = current_user = request.user
    teammates = []
    for teammate in project.teammates.all():
      if teammate.id != user.id:
        teammates.append(teammate)

    # if submitting the form
    if request.method == "POST":
      # get string with all emails
      emailStr = request.POST.get("teammates")
      # separate emails
      emails = emailStr.split(", ")
      print(emails)
      # find ALL users in database
      users_already_signed_up = User.objects.all()
      # see if any match the list of emails
      found_users = User.objects.filter(email__in = emails)
      print(found_users)

      for user in found_users:
        # send invite email to all found users
        msg_plain = render_to_string('emails/added_to_project.txt', {'project_name': project.name})
        msg_html = render_to_string('emails/added_to_project.html', {'project_name': project.name})
        send_mail(
        f'BugTracker: You\'ve been added to {project.name}',
        msg_plain,
        settings.EMAIL_HOST_USER,
        [f'{user.email}'],
        html_message=msg_html,
        fail_silently=False,
        )
        # add user to project
        user_object = User.objects.get(email=user.email)
        project.teammates.add(user_object)
        project.save()
        # finally remove email from list of emails
        emails.remove(user.email)
      
      if len(emails) and emails[0] != '':
        # remaining emails will be new users
        for email in emails:
          # create new user
          random_password = User.objects.make_random_password()
          generated_username = generate_username(email)
          new_user = User.objects.create_user(generated_username, email, random_password)
          new_user.save()
          # send invite email
          msg_plain = render_to_string('emails/new_user_email.txt', {'project_name': project.name, 'username': generated_username, 'password': random_password})
          msg_html = render_to_string('emails/new_user_email.html', {'project_name': project.name, 'username': generated_username, 'password': random_password})
          send_mail(
          f'BugTracker: You\'ve been invited to {project.name}',
          msg_plain,
          settings.EMAIL_HOST_USER,
          [f'{email}'],
          html_message=msg_html,
          fail_silently=False,
          )
          # add new user to project
          new_user_object = User.objects.get(email=email)
          project.teammates.add(new_user_object)
          project.save()

          # redirect to project page
          return redirect('project_detail', project_id=project.id)

    # if GET request, show the form
    return render(request, 'projects/add_teammates.html', {
      'project': project,
      'projects': projects
      })


@login_required
def add_project(request):
    # get all projects
    projects = Project.objects.filter(teammates=request.user)

    # if submitting the form
    if request.method == "POST":
      # create project in database
      project_name = request.POST.get("pname")
      p = Project(name=project_name)
      p.save()

      # add current user as teammate
      current_user = request.user
      p.teammates.add(current_user)
      p.save()

      print(request.POST.get("teammates"))
      # get string with all emails
      emailStr = request.POST.get("teammates")
      # separate emails
      emails = emailStr.split(", ")
      print(emails)
      # find ALL users in database
      users_already_signed_up = User.objects.all()
      # see if any match the list of emails
      found_users = User.objects.filter(email__in = emails)
      print(found_users)

      for user in found_users:
        # send invite email to all found users
        msg_plain = render_to_string('emails/added_to_project.txt', {'project_name': project_name})
        msg_html = render_to_string('emails/added_to_project.html', {'project_name': project_name})
        send_mail(
        f'BugTracker: You\'ve been invited to {project_name}',
        msg_plain,
        settings.EMAIL_HOST_USER,
        [f'{user.email}'],
        html_message=msg_html,
        fail_silently=False,
        )
        # add user to project
        user_object = User.objects.get(email=user.email)
        p.teammates.add(user_object)
        p.save()
        # finally remove email from list of emails
        emails.remove(user.email)

      if len(emails) and emails[0] != '':
        # remaining emails will be new users
        for email in emails:
          # create new user
          random_password = User.objects.make_random_password()
          generated_username = generate_username(email)
          new_user = User.objects.create_user(generated_username, email, random_password)
          new_user.save()
          # send invite email
          msg_plain = render_to_string('emails/new_user_email.txt', {'project_name': project_name, 'username': generated_username, 'password': random_password})
          msg_html = render_to_string('emails/new_user_email.html', {'project_name': project_name, 'username': generated_username, 'password': random_password})
          send_mail(
          f'BugTracker: You\'ve been invited to {project_name}',
          msg_plain,
          settings.EMAIL_HOST_USER,
          [f'{email}'],
          html_message=msg_html,
          fail_silently=False,
          )
          # add new user to project
          new_user_object = User.objects.get(email=email)
          p.teammates.add(new_user_object)
          p.save()

      # redirect to project page
      return redirect('project_detail', project_id=p.id)

    # if GET request, show the form
    return render(request, 'projects/create.html', {'projects': projects})

@login_required
def project_detail(request, project_id):
    projects = Project.objects.filter(teammates=request.user)
    project = Project.objects.get(id=project_id)
    does_have_teammates = project.teammates.all().count() > 1
    current_user = request.user
    print(project.teammates.all())
    return render(request, 'projects/detail.html', {
        'project': project,
        'does_have_teammates': does_have_teammates,
        'current_user': current_user,
        'projects': projects
    })

@login_required
def create_bug(request):
    projects = Project.objects.filter(teammates=request.user)
    user = request.user

    # if submitting the form
    if request.method == "POST":
      # create bug in database
      title = request.POST.get("bug_title")
      description = request.POST.get("description")
      file_name = request.POST.get("file_name")
      project_id = request.POST.get("project")
      print(project_id)
      project = Project.objects.get(id=project_id)
      bug = Bug(title=title, description=description, file_name=file_name, project=project, user=user)
      bug.save()

      # redirect to bug detail page
      return redirect('bug_detail', bug_id=bug.id)

    # if GET request, show the form
    return render(request, 'bugs/create_bug.html', {'projects': projects})

@login_required
def add_bug_to_project(request, project_id):
    projects = Project.objects.filter(teammates=request.user)
    project = Project.objects.get(id=project_id)
    user = request.user

main_app/templates/bugs/create_bug.html
{% extends 'extended-base.html' %}

{% block child %}
    <h1 class="display-4 title center-text addition-title">Create New Bug</h1>

    {% if projects|length > 0 %}

    <form action="{% url 'create_bug' %}" method="post" class="form">
        {% if error_messsage %}<p class="red-text">{{ error_message }}</p>{% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="bug_title">Bug Title:</label>
            <input type="text" name="bug_title" class="form-control">
        </div>

        <div class="form-group">
            <label for="project">Project</label>
            <select class="form-control" id="project" name="project">
                {% for project in projects %}
                    <option value={{project.id}}>{{project.name}}</option>
                {% endfor %}
            </select>
          </div>

        <div class="form-group">
            <label for="description">Short description of the bug:</label>
            <textarea type="text" name="description" class="form-control" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="file_name">File Name where the bug occurs:</label>
            <input type="text" name="file_name" class="form-control">
        </div>
        <input type="submit" value="Submit" class="btn btn-success">
    </form>

    {% else %}
        <p class="center-text">You need to create a project first.</p>
        <a class="center-text" href="{% url 'project_create' %}"><button class="btn btn-primary btn-sm create-project-link">+ Add Project</button></a>
    {% endif %}

{% endblock %}

main_app/templates/bugs/create_project_bug.html
{% extends 'extended-base.html' %}

{% block child %}
    <h1 class="display-4 title center-text addition-title">Add New Bug to {{ project.name }}</h1>

    <form action="{% url 'project_bug_create' project.id %}" method="post" class="form">
        {% if error_messsage %}<p class="red-text">{{ error_message }}</p>{% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="bug_title">Bug Title:</label>
            <input type="text" name="bug_title" class="form-control">
        </div>
        <div class="form-group">
            <label for="description">Short description of the bug:</label>
            <textarea type="text" name="description" class="form-control" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="file_name">File Name where the bug occurs:</label>
            <input type="text" name="file_name" class="form-control">
        </div>
        <input type="submit" value="Submit" class="btn btn-success">
    </form>

{% endblock %}

main_app/templates/bugs/detail.html
{% extends 'extended-base.html' %}

{% block child %}

<div class="bug-display">
    <div class="bug-left">
        <h1 class="display-4 title">{{ bug.title }}</h1>
    
            {% if bug.resolved %}
            <p class="resolved"> Resolved! </p>
            <a href="{% url 'delete_bug' bug.id %}"><button type="button" class="btn btn-danger delete">Delete</button></a>
            {% endif %}
    
            <p>Logged by {{ bug.user }} <span class="bug-creation-time">{{bug.created_at}}</span></p>
    
            <p>Bug Description: {{ bug.description }}</p>
    
            <p>File where bug occurs: {{ bug.file_name }}</p>
    
            {% if bug.resolved == False %}

            <div class="upload">
                <p>Add Bug Screenshot:</p>
                
                <form 
                    action="{% url 'add_screenshot' bug.id %}"
                    enctype="multipart/form-data"
                    method="POST"
                    class="card-panel"
                    >
                    {% csrf_token %}
                    <div class="input-group">
                        <div class="custom-file">
                          <input name="photo-file" type="file" class="custom-file-input" id="inputGroupFile04">
                          <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Upload">
                </form>
            </div>
        
            <form action="{% url 'resolve_bug' bug.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-success btn-lg" value="Mark as Resolved">
            </form>
        {% endif %}
    </div>
    
    <div class="bug-right">
        {% for screenshot in bug.screenshot_set.all %}
            <figure>
                <img src="{{screenshot.url}}" class="img-fluid" alt="bug screenshot">
                <figcaption>Uploaded by {{ screenshot.user }} at {{ screenshot.created_at }}</figcaption>
            </figure>
            
        {% empty %}
            <div>No Screenshots</div>
        {% endfor %}
    </div>


</div>

<hr>

<div class="bug-comment-section">
    {% for comment in bug.comment_set.all %}
        <div class="comment">
            <p class="comment-date">{{ comment.created_at }}</p>
            <p><span>{{ comment.user }}: </span>{{ comment.text }} </p>
        </div>
            
        {% empty %}
            <p>No Comments</p>
        {% endfor %}

        <form action="{% url 'add_comment' bug.id %}" method="post" class="comment-input">
            {% csrf_token %}
            <div class="form-group">
                <label for="text"></label>
                <textarea class="form-control" name="text" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-info">Add Comment</button>
        </form>
</div>

<script>
    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function() {
      let fileName = $(this).val().split("\\").pop();
      let shortFileName = fileName.length > 10 ? fileName.substring(0, 10) + "..." : fileName
      $(this).siblings(".custom-file-label").addClass("selected").html(shortFileName);
    });
    </script>

{% endblock %}